tasks:
  - name: Backend
    init: |
      cargo build
      cp .env.example .env
    command: |
      export GP_URL=$(gp url)
      export GH_REDIRECT_URL="${GP_URL:0:8}8000-${GP_URL:8}/auth/github"
      export ROCKET_PORT=8000
      make
  - name: Build frontend
    init: |
      cd marketplace && pnpm install
    command: cd /workspace/*/marketplace && nodemon
image:
  file: gitpod.Dockerfile
ports:
  - port: 6379
    onOpen: ignore
  - port: 54320
    onOpen: ignore
vscode:
  extensions:
    - https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-linux-x64.vsix
    - serayuzgur.crates
    - bungcip.better-toml
