tasks:
  - name: Backend
    init: |
      cargo install diesel_cli --no-default-features -F postgres
      cargo build -p server
    command: make
  - name: Build frontend
    init: |
      npm install --global nodemon
      cd marketplace && pnpm install
    command: cd marketplace && nodemon
ports:
  - port: 6379
    onOpen: ignore
  - port: 54320
    onOpen: ignore
vscode:
  extensions:
    - https://github.com/rust-lang/rust-analyzer/releases/latest/download/rust-analyzer-linux-x64.vsix
    - serayuzgur.crates
    - tamasfe.even-better-toml
