[phases.name]
nixOverlays = ['https://github.com/oxalica/rust-overlay/archive/master.tar.gz']
[phases.setup]
nixPkgs = ['nodejs', "rust-bin.nightly.latest.default", "gcc", "glibc"]
[phases.svelte-install]
dependsOn = ["...", "setup"]
cacheDirectories = ['marketplace/node_modules/.cache']
cmds = [
  'cd marketplace && npm i'
]
[phases.svelte-build]
dependsOn = ["...", "svelte-install"]
cmds = [
  'cd marketplace && node_modules/.bin/vite build',
]
[phases.build]
cacheDirectories = ['...', '~/.cargo/git', '~/.cargo/registry', 'target']
dependsOn = ["...", "svelte-build"]
cmds = [
  'cargo build -r',
]
[start]
cmd = "./target/release/server"
