[theme]
name = "Blackest"

[theme.base]
white = "#FFFFFF"
black = "#000000"
grey = "#111111"
blue = "#0000FF"
red = "#FF0000"
yellow = "#FFFF00"
orange = "#FF5A00"
green = "#00FF00"
purple = "#770077"
cyan = "#00FFFF"
magenta = "#FF00FF"

[theme.syntax]
attribute = "$yellow"
boolean = "$blue"
builtinType = "$cyan"
character = "$purple"
comment = "#5C6370"
conditional = "$blue"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
exception = "$red"
field = "$red"
float = "$yellow"
function = "$blue"
"function.method" = "$blue"
include = "$magenta"
interface = "$yellow"
keyword = "$purple"
method = "$blue"
number = "$yellow"
parameter = "$red"
property = "$red"
"punctuation.bracket" = "$blue"
"punctuation.delimiter" = "$orange"
repeat = "$green"
selfKeyword = "$purple"
string = "$green"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
"variable.other.member" = "$red"

[theme.ui]
"activity.background" = "#303030"
"activity.current" = "$black"
"completion.background" = "#000000"
"completion.current" = "#303030"
"editor.background" = "$black"
"editor.caret" = "#FFFFFF7F"
"editor.current_line" = "#101010"
"editor.dim" = "#5C6370"
"editor.focus" = "#FFFFFF"
"editor.foreground" = "$white"
"editor.link" = "$cyan"
"editor.selection" = "#007FFF50"
"error_lens.error.background" = "#FF000020"
"error_lens.error.foreground" = "#FF0000"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "#5C6370"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#000000"
"inlay_hint.background" = "#000000"
"inlay_hint.foreground" = "#FFFFFF20"
"lapce.active_tab" = "$blue"
"lapce.border" = "#333333"
"lapce.dropdown_shadow" = "#0000FF"
"lapce.error" = "$red"
"lapce.inactive_tab" = "$grey"
"lapce.scroll_bar" = "#303030"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "#898989"
"palette.background" = "$black"
"palette.current" = "$grey"
"panel.background" = "$black"
"panel.current" = "$grey"
"panel.hovered" = "#454545"
"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "#00507f"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"
"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "$grey"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#FFFFFF"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = "Cantarell"
font-size = 10
header-height = 30
status-height = 25
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = "JetBrains Mono"
hover-font-size = 0
