name: Clippy

on: [ pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Clippy
      run: rustup component add clippy-preview && cargo clippy --verbose
